### ISSUE TITLE
names of png plot files

### ISSUE THREAD

**Issue by teuben** [amanchokshi/mwa-satellites#10]
some of the CLI commands that produce a figure in the example, don't actually report
their filename to the screen. E.g. ephem_single and align_single, and probably more?
Since this is an example, would be nice to either add it to the text, or perhaps
better, let the command print it out.

**Comment by amanchokshi** [comment]
Do you mean print out the path to the output png file? That would be pretty straightforward. 

```
$ align_single
Saving sample savgol_interp plot to: ./embers_out/rf_tools
```
Currently, the cli tools print out the directory to which the plots are saved

**Comment by teuben** [comment]
Well, the directory is useful too, but sometimes that directory has a lot of (png)/files in it.  If it's just one file produced, why not give that name. then user can copy and paste and get it on screen in one shot. Now, if you run this command in a loop where you could have many plot files, it would be annoying again. So, pick your poising.

**Comment by amanchokshi** [comment]
Makes sense. I'll modify the scripts which only output single files, to print out the full path to the file.  I'll leave the batch tools as is.

**Comment by amanchokshi** [comment]
Okay, all cli-tools which create a single plot now print out the full path to the png file. The example in the documentation have been updated too. 

Can you update EMBERS to the latest version - 0.8.0 to see the changes when you use the tools
