### ISSUE TITLE
location of example files.

### ISSUE THREAD

**Issue by teuben** [amanchokshi/mwa-satellites#7]
In the first example:

_The above creates an EMBERS directory, within which we can run our example code. Outputs will by default, be saved to ~/EMBERS/embers_out.

It would be good to clarify that if I had created   /foobar/EMBERS, the output would be by default in  /foobar/EMBERS/embers_out

Since ~ is somewhat special, i was worried my already small homedirectory (see previous issue) would be in danger again. I'm sure you did it the right way, but a clarification would be in place here....

**Comment by amanchokshi** [comment]
Thank Peter, I've updated the documentation with your suggestion.  Very valid that people know that the home directory is nothing special and any path will work.
