### ISSUE TITLE
kindle?

### ISSUE THREAD

**Issue by teuben** [amanchokshi/mwa-satellites#9]
there is an empty section labeled "kindle", which i'm sure is not the reading gadget.  Maybe add some words what this is for? It's not immediately obvious to me.

**Comment by amanchokshi** [comment]
The EMBERS package contains a sub-module `embers.kindle` of python scripts which are the cli-tools which I refer to in the examples. I've added them as `console_scripts` using entry points in my `setup.py`.

I will flesh out the kindle section with a proper description and a link to the examples.

**Comment by amanchokshi** [comment]
The documentation for embers.kindle has now been completed along with an appropriate introduction.
